service: sggsjbe

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-south-1

functions:
  app:
    handler: lambda.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any
